### ISSUE TITLE
Not working on Homey v 0.9.3

### ISSUE THREAD

**Issue by lubbertkramer** [Sillyjan/net.sillyjan.nzbget#1]
Homey version:
0.9.3

App store NZBget version:
0.0.1

What is going wrong:
After installation getting a red warning signal and when pressing the red wawrning i'm seeing error 

Error: Cannot find module './parts/common'
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/node_modules/parse-torrent-name/index.js:3:1)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)

**Comment by Sillyjan** [comment]
Fixed in version 0.0.2
Seems some files where missing do to the .gitignore file
